# =============================================
# KONFIGURASI DATABASE
# =============================================
spring.datasource.url=jdbc:mysql://localhost:3306/reservasi_ruang?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================================
# KONFIGURASI HIBERNATE / JPA
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# =============================================
# KONFIGURASI THYMELEAF
# =============================================
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

# =============================================
# KONFIGURASI SERVER
# =============================================
server.port=8080
spring.application.name=Sistem Reservasi Ruang

# =============================================
# AKUN STARTER
# =============================================
app.starter-users.enabled=true
app.starter-users.mahasiswa.username=mhs
app.starter-users.mahasiswa.password=mhs
app.starter-users.admin.username=adm
app.starter-users.admin.password=adm
app.starter-users.satpam.username=stm
app.starter-users.satpam.password=stm
